# Generated by Django 5.0 on 2024-01-01 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0002_remove_inspo_gallery_id_remove_inspo_board_id_and_more'),
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='creator.creator')),
            ],
        ),
        migrations.CreateModel(
            name='Inspo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('column_coordinate', models.IntegerField()),
                ('row_coordiantes', models.IntegerField()),
                ('column_length', models.IntegerField()),
                ('row_length', models.IntegerField()),
                ('board_ID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.board')),
                ('gallery_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.gallery')),
            ],
        ),
    ]
