# Generated by Django 5.0 on 2024-01-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspo',
            name='column_coordinate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspo',
            name='column_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspo',
            name='row_coordiantes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspo',
            name='row_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
