# Generated by Django 5.0 on 2024-01-01 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspo',
            name='gallery_ID',
        ),
        migrations.RemoveField(
            model_name='inspo',
            name='board_ID',
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
        migrations.DeleteModel(
            name='Inspo',
        ),
    ]
